### PR TITLE
Fixing two failing tests

### PR DESCRIPTION
**Pull request by HuangStanley050**
Fixed hack-detail.test.js and HacksPage.test.js plus fixed a warning for Login.test.js

### CODE REVIEW

**Comment by HuangStanley050** [comment]
This PR still misses some of the fixes from PR 26 in the Login.test

**Comment by jpeyper** [comment]
To avoid this happening in the future, you should add a workflow to run just the tests (not the deployment) on a PR.

https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request

**Comment by HuangStanley050** [comment]
implemented unit test on PR with github action. This is a great idea, we can clearly see if a PR fails or not, if successful then can merge with master.

**Comment by HuangStanley050** [comment]
cancelling this PR to try open another one, rebase might have gone funny.

**Pull request closed without merging**
